/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.virtusa.jenkins;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("First test case", classUnderTest.getGreeting());
    }
}
